### ISSUE TITLE
使用する言語、ライブラリを決定する

### ISSUE THREAD

**Issue by inoh** [systemlink/e-sche#1]
@tigawa @masashiAbe

必要そうなGemを何個かピックアップして追加しました。
とりあえずの必要な言語、ライブラリは下記を考えています。

### 必須

* Grape
* rspec
* Backbone.js
* Marionette.js  
~~※React.jsなら不要~~
* CoffeeScript

### 要検討

~~* CoffeeScript~~

他学習が必要なものがあれば随時追加していきます。

**Comment by fukuishere** [comment]
@inoh 
福田です！この度はいろいろ無理いってすみません。。

早速ですが、ライブラリは CoffeeScript は使用された方が良いかとおもいまっす！
あと、 CSS フレームワークとして Bootstrap もあればよいかとおもいます。

Backbone のデータバインディングとして `backbone stickit` も こちらでは使用しています。

**Comment by fukuishere** [comment]
あ、 #5 で bootstrap の導入がありましたね。。
すみません、見逃していました。。

**Comment by fukuishere** [comment]
ちなみに、react はこれからの新規案件では使っていきたいです！しかし、いまは backbone を採用するプロジェクトが多いので、本プロダクトでは、backbone でOKっす！

**Comment by inoh** [comment]
@fukuishere 
いろいろアドバイスありがとうございます :smile:
こちらこそ力不足な点が多々あると思いますがよろしくお願いします！
backboneとかcoffeeとか少し怪しいので事前に予習しておきますね

**Comment by inoh** [comment]
使用しているライブラリあちこちに書いててわかりにくかったですね :astonished:
現時点で整理した使用予定のライブラリはこんな感じです。
https://github.com/systemlink/e-sche/blob/i3/README.md

**Comment by inoh** [comment]
ブランチが最新だったのでmasterにマージ最新化しました

https://github.com/systemlink/e-sche/blob/master/README.md
