### ISSUE TITLE
イベント候補日が対象者に通知できる

### ISSUE THREAD

**Issue by inoh** [systemlink/e-sche#13]

**Comment by masashiAbe** [comment]
トップページにイベント一覧が表示され、イベント選択すると候補日選択機能の画面になる。回答者の操作としてはそんな流れでどうでしょうか？

**Comment by masashiAbe** [comment]
候補日選択機能は、#12にありましたね。要するに『「イベント」が対象者に通知できる』でいいのかなと思った次第。

**Comment by inoh** [comment]
基本ちょー助をベースにできたらと思います。
私の頭の中ではイベントの一覧はいらなくて通知用URLが登録後に照会できればよいかなぁ。

**Comment by inoh** [comment]
ちょー助の目的って「イベント内容」ではなくてあくまで「イベント日」をみんなで決定するものだという認識です。
なのであえてissueは「イベント候補日」としています。
実際はタイトルとか内容もあるので「イベント」でもよいかと思います

**Comment by inoh** [comment]
完了の定義

1. サーバーからイベントデータを返す  
@masashiAbe 担当
1. イベントデータよりイベント参加登録画面のURLを表示する  
@inoh 担当

**Comment by inoh** [comment]
#18 
#19 
に分割しissueはクローズとする

**Comment by inoh** [comment]
#18 
->
#25
