### ISSUE TITLE
サーバからイベントデータを返す。（grapeを使用する）

### ISSUE THREAD

**Issue by masashiAbe** [systemlink/e-sche#25]
#18のブランチはgemの追加のみでマージしたので、再度やります。

**Comment by inoh** [comment]
よろしくお願いします！
私の方もフロント周りは引き続き作業します

**Comment by inoh** [comment]
ちなみにこのissueは
#18 
と同じな気がしますが何か意図がありますか？

**Comment by inoh** [comment]
push単位でissueを作るわけではないのでi18ブランチを継続して使用してもよいですよ

**Comment by masashiAbe** [comment]
i25でpushしてしまいました。
次よりそのように気を付けますという事で良いですか？

**Comment by inoh** [comment]
私の勘違いだったら申し訳ないですがpushで同時にissueもできましたか？
branch名のi25とissueは特に関連づいていないと思います
issueで進捗とか課題を管理したいので同じようなissueであればどちらかをクローズできるとよいです

**Comment by inoh** [comment]
もしかして

i25ブランチ作成
->
issue作成

という流れですかね？
であればi18クローズしてもらってもよいです

**Comment by inoh** [comment]
ちなみに #18 の対応であればサーバからデータを取得するだけなのでPOSTに関しては別issueを立ててやってもらうのがよいと思います

**Comment by masashiAbe** [comment]
なんらかの変更をマージすることで一つの区切りとすると思い、#18はあれで終わりとするもんだと考えてました。#18をクローズしましょう。
pushと同時にissueが出来たわけではないです。

**Comment by inoh** [comment]
その辺りはプロジェクトの方針だと思いますけどねー
今回は進行の都合上マージしちゃいましたが本来なら区切りじゃないとマージはしないかと思います
#18 のクローズお願いします！

**Comment by inoh** [comment]
@masashiAbe 
イベントデータの取得で候補日付の一覧が取得できるように対応をお願いします。

**Comment by inoh** [comment]
進捗がわかりにくくなってきたのでイベントの候補日を取得するissueを作成してみました。
現状候補日の取得以外でイベントデータの取得が問題なければ当issueクローズでよいと思いますがどうでしょう？

**Comment by inoh** [comment]
#35 
候補日一覧取得のissueです

**Comment by masashiAbe** [comment]
イベントデータの取得には問題ないためクローズします。

**Comment by masashiAbe** [comment]
イベントデータ取得には問題ないためクローズします。
