### ISSUE TITLE
i18をcommitしたユーザについて

### ISSUE THREAD

**Issue by masashiAbe** [systemlink/e-sche#26]
m-abe というユーザ名に違和感があります。どうも、ぴーぽっぽをさくら＃２へ配備するために、会社のメールアドレスで作ったものと思われます。新たに'masashiAbe'用のメールアドレスでSSHキー設定したらいいのでしょうか？

**Comment by inoh** [comment]
私的にm-abeというユーザに違和感はかんじませんがどうなんでしょう
SSHキー再設定しても何も変わらないんじゃないですかね？

**Comment by masashiAbe** [comment]
e-sche/.git/configに[user]が無かったため、$HOME/.gitconfigを参照した様です。
e-sche/.git/configに[user]を追加することで解決。
