### ISSUE TITLE
AngularJSを導入する

### ISSUE THREAD

**Issue by inoh** [systemlink/e-sche#28]
@fukuishere
わかればでよいのでAngularJSについて２点ほど質問させてくださーい！

1. バージョンは 1 or 2 ?
2. 環境は Rails or Grunt ?

よろしくお願いします！

**Comment by inoh** [comment]
@fukuishere
もう一つ気になっていたので追加で質問お願いします！
フロント周りはAngularJSでよいのですが並行してサーバ周りはGrapeでよいでしょうか？
新しいRailsではjbuilderがあるのでそっち路線がこれから主流かなぁと思っていました。
重ねて質問申し訳ないです。
よろしくお願いします！

**Comment by inoh** [comment]
AngularJS + Rails で調べてみましたがいろいろと難しいですね。
AngularJSだとワンページ前提の設計になっていてrailsのroutesがうまく共存するのが難しいです。
方法としては下記の２パターンがありそう。

1. フロントはpublicフォルダ配下で管理しRailsに依存しない
1. フロントはassets配下で管理しRailsに依存させる

前者はangularの世界で生きていけるので構成はシンプルとなるがrailsのコントローラを通さないので認証とかできない。
あとSprocketsもきかないのでcoffeescriptとか連結とかminifyとかも無理。
後者はrailsのコントローラを通すので認証とか共有できるがangularとルーティングが喧嘩して何かと制御が複雑。

今回はangularjsに学習コストをかけたいので前者がよいかなぁと考えています。

**Comment by inoh** [comment]
前者ならnode入れてgrunt管理かなぁ

**Comment by fukuishere** [comment]
@inoh 
回答遅くなってすみません！
うちの方針として 「Angularでいくぜー！」みたいなのはまだ正直ないです。
ですので、Angular のプロジェクトも数本ありますが、Rails を使うプロジェクトで Angular の選択肢はまだないかなと考えています。
（Rails プロジェクトで Angular を使うなら Backbone or React にしたいのがいまの僕の気持ちです）

それを踏まえてご回答すると、
> 環境は Rails or Grunt ?
Angular の案件は Rails を使わずに、
Bower + Gulp で開発してます！

> フロント周りはAngularJSでよいのですが並行してサーバ周りはGrapeでよいでしょうか？
> 新しいRailsではjbuilderがあるのでそっち路線がこれから主流かなぁと思っていました。

フロントフレームワークと併用するならGrape でなくても良いっす！
ですが、もしまだ Grape をお使いになられていなかったら WebAPI の開発案件は Grape が主ですので、Grape の開発に慣れるという目的で使っても良いかなとおもてます！

**Comment by inoh** [comment]
@fukuishere 
回答ありがとうございます！

> Rails プロジェクトで Angular を使うなら Backbone or React にしたいのがいまの僕の気持ちです
> Bower + Gulp で開発してます！

納得了解です
Gulpは初めて聞きました
Gruntはjavascriptで組むときに使ってましたがGulp調べてみようと思います

> Grape の開発に慣れるという目的で使っても良いかなとおもてます！

Grapeはほとんど経験がないのでサーバ周りは引き続きGrapeでやろうと思います！
